# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.0.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.0.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/samdoiron/Code/C++/HACK

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/samdoiron/Code/C++/HACK

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.0.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.0.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/samdoiron/Code/C++/HACK/CMakeFiles /Users/samdoiron/Code/C++/HACK/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/samdoiron/Code/C++/HACK/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hack

# Build rule for target.
hack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hack
.PHONY : hack

# fast build rule for target.
hack/fast:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/build
.PHONY : hack/fast

ainstruction.o: ainstruction.cc.o
.PHONY : ainstruction.o

# target to build an object file
ainstruction.cc.o:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/ainstruction.cc.o
.PHONY : ainstruction.cc.o

ainstruction.i: ainstruction.cc.i
.PHONY : ainstruction.i

# target to preprocess a source file
ainstruction.cc.i:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/ainstruction.cc.i
.PHONY : ainstruction.cc.i

ainstruction.s: ainstruction.cc.s
.PHONY : ainstruction.s

# target to generate assembly for a file
ainstruction.cc.s:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/ainstruction.cc.s
.PHONY : ainstruction.cc.s

cinstruction.o: cinstruction.cc.o
.PHONY : cinstruction.o

# target to build an object file
cinstruction.cc.o:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/cinstruction.cc.o
.PHONY : cinstruction.cc.o

cinstruction.i: cinstruction.cc.i
.PHONY : cinstruction.i

# target to preprocess a source file
cinstruction.cc.i:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/cinstruction.cc.i
.PHONY : cinstruction.cc.i

cinstruction.s: cinstruction.cc.s
.PHONY : cinstruction.s

# target to generate assembly for a file
cinstruction.cc.s:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/cinstruction.cc.s
.PHONY : cinstruction.cc.s

hack.o: hack.cc.o
.PHONY : hack.o

# target to build an object file
hack.cc.o:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/hack.cc.o
.PHONY : hack.cc.o

hack.i: hack.cc.i
.PHONY : hack.i

# target to preprocess a source file
hack.cc.i:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/hack.cc.i
.PHONY : hack.cc.i

hack.s: hack.cc.s
.PHONY : hack.s

# target to generate assembly for a file
hack.cc.s:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/hack.cc.s
.PHONY : hack.cc.s

instruction.o: instruction.cc.o
.PHONY : instruction.o

# target to build an object file
instruction.cc.o:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/instruction.cc.o
.PHONY : instruction.cc.o

instruction.i: instruction.cc.i
.PHONY : instruction.i

# target to preprocess a source file
instruction.cc.i:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/instruction.cc.i
.PHONY : instruction.cc.i

instruction.s: instruction.cc.s
.PHONY : instruction.s

# target to generate assembly for a file
instruction.cc.s:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/instruction.cc.s
.PHONY : instruction.cc.s

invalidsyntaxexception.o: invalidsyntaxexception.cc.o
.PHONY : invalidsyntaxexception.o

# target to build an object file
invalidsyntaxexception.cc.o:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/invalidsyntaxexception.cc.o
.PHONY : invalidsyntaxexception.cc.o

invalidsyntaxexception.i: invalidsyntaxexception.cc.i
.PHONY : invalidsyntaxexception.i

# target to preprocess a source file
invalidsyntaxexception.cc.i:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/invalidsyntaxexception.cc.i
.PHONY : invalidsyntaxexception.cc.i

invalidsyntaxexception.s: invalidsyntaxexception.cc.s
.PHONY : invalidsyntaxexception.s

# target to generate assembly for a file
invalidsyntaxexception.cc.s:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/invalidsyntaxexception.cc.s
.PHONY : invalidsyntaxexception.cc.s

label.o: label.cc.o
.PHONY : label.o

# target to build an object file
label.cc.o:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/label.cc.o
.PHONY : label.cc.o

label.i: label.cc.i
.PHONY : label.i

# target to preprocess a source file
label.cc.i:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/label.cc.i
.PHONY : label.cc.i

label.s: label.cc.s
.PHONY : label.s

# target to generate assembly for a file
label.cc.s:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/label.cc.s
.PHONY : label.cc.s

program.o: program.cc.o
.PHONY : program.o

# target to build an object file
program.cc.o:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/program.cc.o
.PHONY : program.cc.o

program.i: program.cc.i
.PHONY : program.i

# target to preprocess a source file
program.cc.i:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/program.cc.i
.PHONY : program.cc.i

program.s: program.cc.s
.PHONY : program.s

# target to generate assembly for a file
program.cc.s:
	$(MAKE) -f CMakeFiles/hack.dir/build.make CMakeFiles/hack.dir/program.cc.s
.PHONY : program.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... hack"
	@echo "... rebuild_cache"
	@echo "... ainstruction.o"
	@echo "... ainstruction.i"
	@echo "... ainstruction.s"
	@echo "... cinstruction.o"
	@echo "... cinstruction.i"
	@echo "... cinstruction.s"
	@echo "... hack.o"
	@echo "... hack.i"
	@echo "... hack.s"
	@echo "... instruction.o"
	@echo "... instruction.i"
	@echo "... instruction.s"
	@echo "... invalidsyntaxexception.o"
	@echo "... invalidsyntaxexception.i"
	@echo "... invalidsyntaxexception.s"
	@echo "... label.o"
	@echo "... label.i"
	@echo "... label.s"
	@echo "... program.o"
	@echo "... program.i"
	@echo "... program.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

